# Generated by Django 6.0.2 on 2026-02-07 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, default='', max_length=200)),
                ('input_params', models.JSONField(default=dict, help_text='Research parameters: query, mode, year_filter, llm_provider')),
                ('output_data', models.JSONField(blank=True, help_text='Research results: papers, ideas, report_sections, report_formats', null=True)),
                ('error_data', models.JSONField(blank=True, help_text='Error details if task failed: code, message, traceback', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Research Task',
                'verbose_name_plural': 'Research Tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='research_re_status_a3c4a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('LLM', 'LLM Service'), ('SEARCH', 'Search Service')], db_index=True, max_length=20)),
                ('error_code', models.CharField(db_index=True, max_length=50)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, default='')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='research.researchtask')),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
